import base64
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import AsyncGenerator
from uuid import UUID
from fastapi import HTTPException
from sqlalchemy.orm import selectinload
from sqlalchemy import desc, select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.translator import TranslationJob, TranslationPage
from app.utils.ai_client import ai_client
from app.utils.image_utils import resize_image_for_ocr
from app.utils.zip_utils import create_zip_stream as generate_zip_stream
from app.services import file_service


async def process_job_vision(job_id: UUID) -> None:
    """
    Background task for the vision pipeline.
    IMPORTANT: Creates its own DB session — never use a request-scoped session here.
    """
    from app.core.database import AsyncSessionLocal
    
    async with AsyncSessionLocal() as db:
        try:
            await _run_vision_job(db, job_id)
        except Exception as e:
            # Last-resort error catch — update status even if inner function failed
            async with AsyncSessionLocal() as err_db:
                job = await err_db.get(TranslationJob, job_id)
                if job and job.status != "failed":
                    job.status = "failed"
                    job.error_message = f"Unhandled error: {e}"
                    await err_db.commit()
            raise

async def _run_vision_job(db: AsyncSession, job_id: UUID) -> None:
    # Fetch the job and mark as processing
    stmt = select(TranslationJob).where(TranslationJob.id == job_id)
    result = await db.execute(stmt)
    job = result.scalar_one_or_none()
    
    if not job:
        return

    job.status = "processing"
    job.started_at = datetime.now(timezone.utc)
    await db.commit()

    try:
        # Get image paths
        job_dir = file_service.get_upload_dir(job.user_id, job.id)
        original_dir = job_dir / "original"
        image_paths = sorted([str(p) for p in original_dir.glob("*") if p.is_file()])

        # Update page count immediately so frontend pagination is correct
        job.page_count = len(image_paths)
        await db.commit()

        # Process each page
        for page_number, img_path in enumerate(image_paths, start=1):
            
            # Check if the page already exists
            stmt = select(TranslationPage).where(
                TranslationPage.job_id == job_id,
                TranslationPage.page_number == page_number
            )
            result = await db.execute(stmt)
            page = result.scalar_one_or_none()

            if not page:
                page = TranslationPage(
                    job_id=job_id,
                    page_number=page_number,
                    original_path=img_path,
                    processing_status="processing",
                )
                db.add(page)
            else:
                page.processing_status = "processing"
                page.error_message = None
                page.regions_json = None
                page.translated_path = None
                page.has_text = False
                
            await db.commit()
            await db.refresh(page)

            try:
                # Encode image to base64
                with open(img_path, "rb") as f:
                    image_b64 = base64.b64encode(f.read()).decode("utf-8")

                regions = []
                async for chunk in ai_client.translate_image_vision_stream(
                    image_base64=image_b64,
                    source_language=job.source_language,
                    target_language=job.target_language,
                ):
                    # Parse the clean string generated by aiter_lines()
                    if isinstance(chunk, dict):
                        data = chunk
                    else:
                        try:
                            data = json.loads(chunk)
                        except json.JSONDecodeError:
                            print(f"Backend Warning: Could not parse chunk: {chunk}")
                            continue

                    # Handle End of Stream
                    if data.get("done") is True:
                        break
                        
                    if data.get("error"):
                        raise RuntimeError(data["error"])

                    # Handle valid regions
                    if "bbox" in data:
                        regions.append(data)
                        
                        # Live commit so frontend sees progress
                        page.regions_json = json.dumps(regions, ensure_ascii=False)
                        page.has_text = True
                        await db.commit()

                # Guaranteed Save on Success
                page.translated_path = img_path
                page.has_text = len(regions) > 0
                page.processing_status = "completed" if regions else "no_text"
                await db.commit()

            except Exception as e:
                # Fails a single page and breaks the loop safely
                await db.rollback() # Clear any hanging transactions
                
                page.processing_status = "failed"
                page.error_message = str(e)
                await db.commit()
                
                job.status = "failed"
                job.error_message = f"Page {page_number} failed: {str(e)}"
                await db.commit()
                
                print(f"Backend Task Failed on Page {page_number}: {e}")
                break 

        # Mark the entire job as complete (if no pages failed)
        if job.status != "failed":
            job.status = "completed"
            job.completed_at = datetime.now(timezone.utc)
            await db.commit()

    except Exception as e:
        # Catastrophic failure (e.g., file reading errors)
        # NO break statement here!
        await db.rollback()
        job.status = "failed"
        job.error_message = f"Unhandled error: {str(e)}"
        await db.commit()
        print(f"Backend Task Catastrophic Failure: {e}")
        
async def create_zip_stream(job_id: UUID, db: AsyncSession) -> AsyncGenerator[bytes, None]:
    """
    Stream a ZIP of all translated pages without loading all into memory.
    """
    stmt = select(TranslationPage).where(TranslationPage.job_id == job_id).order_by(TranslationPage.page_number)
    result = await db.execute(stmt)
    pages = result.scalars().all()

    file_paths = []
    for page in pages:
        # Use translated path if available, fallback to original
        source_path = page.translated_path or page.original_path
        if source_path and Path(source_path).exists():
            name_in_zip = f"page_{page.page_number:03d}{Path(source_path).suffix}"
            file_paths.append((source_path, name_in_zip))

    # Yield the async generator directly from zip_utils
    async for chunk in generate_zip_stream(file_paths):
        yield chunk
        
# ─── CRUD Helper Methods ──────────────────────────────────────────────────

async def create_translation_job(db: AsyncSession, user_id: UUID, filename: str, file_size: int, source_lang: str, target_lang: str) -> TranslationJob:
    job = TranslationJob(
        user_id=user_id, 
        original_filename=filename, 
        file_path="", 
        file_size_bytes=file_size, 
        source_language=source_lang, 
        target_language=target_lang
    )
    db.add(job)
    await db.commit()
    await db.refresh(job)
    return job

async def update_job_file_path(db: AsyncSession, job_id: UUID, file_path: str) -> TranslationJob:
    job = await db.get(TranslationJob, job_id)
    job.file_path = file_path
    await db.commit()
    await db.refresh(job)
    return job

async def get_user_jobs(db: AsyncSession, user_id: UUID, skip: int, limit: int) -> list[TranslationJob]:
    stmt = select(TranslationJob).where(TranslationJob.user_id == user_id).order_by(desc(TranslationJob.created_at)).offset(skip).limit(limit)
    result = await db.execute(stmt)
    return list(result.scalars().all())

async def get_job_detail(db: AsyncSession, user_id: UUID, job_id: str) -> TranslationJob:
    stmt = select(TranslationJob).where(
        TranslationJob.id == job_id, 
        TranslationJob.user_id == user_id
    ).options(selectinload(TranslationJob.pages))
    
    result = await db.execute(stmt)
    job = result.scalar_one_or_none()
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    return job

async def reset_job_for_retranslation(db: AsyncSession, user_id: UUID, job_id: UUID) -> TranslationJob:
    # Fetch job with pages loaded
    stmt = select(TranslationJob).where(
        TranslationJob.id == job_id, 
        TranslationJob.user_id == user_id
    ).options(selectinload(TranslationJob.pages))
    
    result = await db.execute(stmt)
    job = result.scalar_one_or_none()
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
        
    # Reset Job Level
    job.status = "pending"
    job.error_message = None
    job.completed_at = None
    
    # Reset Page Level (Critical for Pipeline restart)
    for page in job.pages:
        page.processing_status = "pending"
        page.phase_status = "pending"  
        page.regions_json = None       
        page.translated_path = None
        page.error_message = None
        page.has_text = False
        page.processing_ms = None
    
    await db.commit()
    await db.refresh(job)
    return job

async def delete_translation_job(db: AsyncSession, user_id: UUID, job_id: UUID) -> None: # <-- Changed to UUID
    stmt = select(TranslationJob).where(TranslationJob.id == job_id, TranslationJob.user_id == user_id)
    result = await db.execute(stmt)
    job = result.scalar_one_or_none()
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
        
    # Delete from disk
    job_dir = file_service.get_upload_dir(user_id, job.id)
    if job_dir.exists():
        shutil.rmtree(job_dir)
        
    # Delete from DB
    await db.delete(job)
    await db.commit()

async def get_page_file_path(
    db: AsyncSession, 
    user_id: UUID, 
    job_id: UUID, 
    page_num: int, 
    image_type: str
) -> str:
    """
    Retrieves the physical path for a page image.
    Checks ownership and verifies the file exists on the filesystem.
    """
    stmt = select(TranslationPage).join(TranslationJob).where(
        TranslationJob.user_id == user_id,
        TranslationPage.job_id == job_id,
        TranslationPage.page_number == page_num
    )
    result = await db.execute(stmt)
    page = result.scalar_one_or_none()
    
    if not page:
        raise HTTPException(status_code=404, detail=f"Page {page_num} not found for this job")
        
    target_path = page.translated_path if image_type == "translated" else page.original_path
    
    if not target_path or not Path(target_path).exists():
        # If it's the original and it's missing, that's a real 404
        if image_type == "original":
             raise HTTPException(status_code=404, detail="Original image missing on disk")
        # If it's translated and missing, raise 404 so the router can catch and fallback
        raise HTTPException(status_code=404, detail="Translated image not yet generated")
        
    return str(target_path)

async def process_job_pipeline(job_id: UUID) -> None:
    """
    Background task for the 6-stage pipeline.
    Creates its own DB session — never use a request-scoped session here.
    """
    from app.core.database import AsyncSessionLocal
    
    async with AsyncSessionLocal() as db:
        try:
            await _run_pipeline(db, job_id)
        except Exception as e:
            # Last-resort error catch
            async with AsyncSessionLocal() as err_db:
                job = await err_db.get(TranslationJob, job_id)
                if job and job.status != "failed":
                    job.status = "failed"
                    job.error_message = f"Unhandled pipeline error: {e}"
                    await err_db.commit()
            raise


async def _run_pipeline(db: AsyncSession, job_id: UUID) -> None:
    job = await db.get(TranslationJob, job_id)
    if not job:
        return

    # ── Mark job as processing ──────────────────────────────────────────────
    job.status = "processing"
    job.started_at = datetime.now(timezone.utc)
    await db.commit()

    try:
        # ── Get image paths ───────────────────────────────────────────────
        job_dir = file_service.get_upload_dir(job.user_id, job.id)
        original_dir = job_dir / "original"

        # ── CBZ extraction ────────────────────────────────────────────────
        # If the upload is a CBZ/ZIP, extract images before processing.
        # extract_cbz() handles zip-slip, __MACOSX junk, and natural sort.
        raw_files = list(original_dir.glob("*"))
        if len(raw_files) == 1 and raw_files[0].suffix.lower() == ".cbz":
            from app.services.file_service import extract_cbz
            extract_cbz(str(raw_files[0]), str(original_dir))

        # Only pick image files — skip the .cbz itself
        IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".webp"}
        image_paths = sorted(
            [str(p) for p in original_dir.glob("*") if p.suffix.lower() in IMAGE_EXTS],
            key=lambda s: file_service.natural_sort_key(s),
        )

        if not image_paths:
            job.status = "failed"
            job.error_message = "No image files found after extraction."
            await db.commit()
            return
        
        # ── Update page count so frontend knows total pages immediately ───
        job.page_count = len(image_paths)
        await db.commit()

        # ── Create page records ──────────────────────────────────────────
        pages = []
        for page_number, img_path in enumerate(image_paths, start=1):
            stmt = select(TranslationPage).where(
                TranslationPage.job_id == job_id,
                TranslationPage.page_number == page_number
            )
            result = await db.execute(stmt)
            page = result.scalar_one_or_none()

            if not page:
                page = TranslationPage(
                    job_id=job_id,
                    page_number=page_number,
                    original_path=img_path,
                    phase_status="pending",
                    processing_status="processing"
                )
                db.add(page)
            else:
                page.phase_status = "pending"
                page.processing_status = "processing"
                page.error_message = None
                page.regions_json = None
                page.translated_path = None
                page.has_text = False
                
            pages.append(page)

        await db.commit()
        for p in pages:
            await db.refresh(p)

        # ════════════════════════════════════════════════════════════════════════
        # Detection + crop + OCR via unified API
        # ════════════════════════════════════════════════════════════════════════
        all_page_regions = []

        for page, img_path in zip(pages, image_paths):
            try:
                page.phase_status = "detecting" 
                await db.commit()
                
                with open(img_path, "rb") as f:
                    img_b64 = base64.b64encode(f.read()).decode("utf-8")
                
                # CRITICAL ARCHITECTURE FIX: One unified call for Stages 1, 2, and 3
                regions = await ai_client.ocr_pipeline(img_b64)
                
                if not regions:
                    page.phase_status = "completed"
                    page.processing_status = "no_text"
                    page.has_text = False
                    await db.commit()
                    all_page_regions.append([])
                    continue
                
                page.phase_status = "ocr" 
                await db.commit()
                all_page_regions.append(regions)
                
            except Exception as e:
                page.phase_status = "failed"
                page.processing_status = "failed"
                page.error_message = f"Stage 1-3 OCR Pipeline error: {e}"
                await db.commit()
                all_page_regions.append([])

        # ════════════════════════════════════════════════════════════════════════
        # Translation for ALL pages
        # ════════════════════════════════════════════════════════════════════════
        
        for page, regions, img_path in zip(pages, all_page_regions, image_paths):
            if page.phase_status == "failed" or page.processing_status == "no_text":
                continue
                
            try:
                page.phase_status = "translating"
                await db.commit()
                
                # The Hangoff protocol runs transparently inside this call on the AI server
                translated_regions = await ai_client.translate_batch(regions)
                
                # Update DB with final JSON
                page.regions_json = json.dumps(translated_regions, ensure_ascii=False)
                
                # Serve the original image (Frontend handles the UI rendering now)
                page.translated_path = str(img_path) 
                page.has_text = True
                page.phase_status = "done"
                page.processing_status = "completed"
                await db.commit()
                
            except Exception as e:
                page.phase_status = "failed"
                page.processing_status = "failed"
                page.error_message = f"Stage 5 Translation error: {e}"
                await db.commit()

        # ── Mark job complete ────────────────────────────────────────────────────
        # Only mark job completed if it wasn't marked failed by a catastrophic error
        if job.status != "failed":
            job.status = "completed"
            job.completed_at = datetime.now(timezone.utc)
            await db.commit()

    except Exception as e:
        await db.rollback()
        job.status = "failed"
        job.error_message = f"Catastrophic pipeline error: {str(e)}"
        await db.commit()

async def count_translated_pages(db: AsyncSession, user_id: UUID) -> int:
    """
    Returns the total number of successfully translated pages for a user.
    Called by dashboard /stats endpoint.
    Counts TranslationPage rows with processing_status='completed' joined to jobs owned by user.
    """
    stmt = (
        select(func.count(TranslationPage.id))
        .join(TranslationJob, TranslationPage.job_id == TranslationJob.id)
        .where(
            TranslationJob.user_id == user_id,
            TranslationPage.processing_status == "completed",
        )
    )
    result = await db.scalar(stmt)
    return result or 0