"""add_notes_music_groups_wallpaper

Revision ID: 9d2fe0ef5566
Revises: be6cda45d411
Create Date: 2026-03-04 23:09:15.883439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2fe0ef5566'
down_revision: Union[str, None] = 'be6cda45d411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
