"""add_notes_table_and_settings_columns

Revision ID: be6cda45d411
Revises: 1d32ba1b3385
Create Date: 2026-03-04 22:57:26.297680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6cda45d411'
down_revision: Union[str, None] = '1d32ba1b3385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_conversations_user_archived', table_name='chat_conversations')
    op.drop_index('ix_chat_messages_conversation_created', table_name='chat_messages')
    op.drop_index('ix_pomodoro_sessions_user_started', table_name='pomodoro_sessions')
    op.drop_index('ix_translation_jobs_status', table_name='translation_jobs')
    op.drop_index('ix_translation_jobs_user_status', table_name='translation_jobs')
    op.drop_index('ix_translation_pages_phase_status', table_name='translation_pages')
    op.add_column('user_settings', sa.Column('custom_wallpaper', sa.Text(), nullable=True))
    op.add_column('user_settings', sa.Column('music_groups', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'music_groups')
    op.drop_column('user_settings', 'custom_wallpaper')
    op.create_index('ix_translation_pages_phase_status', 'translation_pages', ['job_id', 'phase_status'], unique=False)
    op.create_index('ix_translation_jobs_user_status', 'translation_jobs', ['user_id', 'status'], unique=False)
    op.create_index('ix_translation_jobs_status', 'translation_jobs', ['status'], unique=False)
    op.create_index('ix_pomodoro_sessions_user_started', 'pomodoro_sessions', ['user_id', 'started_at'], unique=False)
    op.create_index('ix_chat_messages_conversation_created', 'chat_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_chat_conversations_user_archived', 'chat_conversations', ['user_id', 'is_archived'], unique=False)
    # ### end Alembic commands ###
